# Generated by Django 2.1.7 on 2019-04-12 04:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_ID', models.CharField(max_length=20)),
                ('report_number', models.CharField(max_length=20)),
                ('issue_date', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('cell_technology', models.CharField(max_length=20)),
                ('cell_manufacturer', models.CharField(max_length=20)),
                ('number_of_cells', models.CharField(max_length=20)),
                ('number_of_cells_in_series', models.CharField(max_length=20)),
                ('number_of_series_strings', models.CharField(max_length=20)),
                ('number_of_diodes', models.CharField(max_length=20)),
                ('product_lenght', models.CharField(max_length=20)),
                ('product_width', models.CharField(max_length=20)),
                ('product_weight', models.CharField(max_length=20)),
                ('superstate_type', models.CharField(max_length=20)),
                ('superstate_manufacturer', models.CharField(max_length=20)),
                ('substrate_type', models.CharField(max_length=20)),
                ('substrate_manufacturer', models.CharField(max_length=20)),
                ('frame_type', models.CharField(max_length=20)),
                ('frame_adhesive', models.CharField(max_length=20)),
                ('encapsulation_type', models.CharField(max_length=20)),
                ('encapsulation_manufacturer', models.CharField(max_length=20)),
                ('junction_box_type', models.CharField(max_length=20)),
                ('junction_box_manufacturer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('is_FI_required', models.CharField(max_length=20)),
                ('FI_frequency', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='model_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Product'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
